### ISSUE TITLE
pressure unit / calculation

### ISSUE THREAD

**Issue by gwaldi70** [tipichris/bbcwx#16]
Hi,
when displaying accuweather data in metric units, the calculation or display of the air pressure is wrong.
E.g. at the moment for Vienna (Austria) it shows 15°C and 102mb. The temperature is OK, but 102mb could be expected on the surface of Mars. Maybe there's just one digit missing. This is independent of the settings of my display or the desklet scale.

Switching to imperial units, everything is OK:
59F, 30.21inHg

If I display openweather data, the air pressure is more reasonable: 1023mb

Another issue is the name of the unit:
mb is NOT a unit. It is called mbar (or hPa)

BTW: my location settings:
EUR|AT|AU009|VIENNA|

cheers, Georg

**Comment by tipichris** [comment]
Hi

The Weather Desklet does not support Acuweather, nor the location format you quote. Are you sure you have reported this to the right desklet. This is the bug tracker for the Weather Desklet, http://cinnamon-spices.linuxmint.com/desklets/view/20. Could you be using the AcuWeather Desklet, http://cinnamon-spices.linuxmint.com/desklets/view/10?

**Comment by gwaldi70** [comment]
Oh, sorry, you're right. Sorry about the confusion.

**Comment by tipichris** [comment]
No problem. And the Weather Desklet does have the mb versus mbar issue, which I will look to addressing in a future release.

**Comment by gwaldi70** [comment]
Hi again, please let me modify my comment: I just installed the weather desklet now.
The mb vs. mbar issue is ok (it displays meaningful values in mbar).
But: the desklet always says "very heavy rain", independent of the weather outside. When going to openweathermap.org, the forecast corresponds more to the reality.
There are more issues like some 404 errors (didn't find or display location?), although the other data (besides the rain issue) are correctly reported; the forecast is not working either (giving just ??? for the next 3 days).
![bildschirmfoto vom 2015-09-08 12 48 44](https://cloud.githubusercontent.com/assets/14176112/9733178/7a091a56-5629-11e5-87b4-8ee1cfa7de08.png)

btw: the location is Vienna, Austria (2761369)
thanks
Georg

**Comment by gwaldi70** [comment]
the 404 error is solved (after restarting the desklet), but the "very heavy rain" remains: this seems to be an openweathermap issue. The data is just not reported correctly in the desklet, but it's correct on the homepage. BBC as data source in the same desklet displays everything perfectly.
Thanks again
Georg

**Comment by tipichris** [comment]
Hi

Seems the German translators spotted the mb / mbar issue. I've put this in a separate issue as it still needs sorting out for many languages, including English.

As you say, the other issues seem to be with the data providers. Openweather seems intermittent right now. Seems slightly more reliable for Vienna if you use `48.21,16.37` as the location, but still gives occasional 404s. The Openweather api is reporting current conditions as

`{"coord":{"lon":16.37,"lat":48.21},"weather":[{"id":503,"main":"Rain","description":"very heavy rain","icon":"10d"}],"base":"cmc stations","main":{"temp":290.65,"pressure":1023,"humidity":42,"temp_min":288.85,"temp_max":293.15},"wind":{"speed":3.6,"deg":330},"rain":{"1h":176.11},"clouds":{"all":0},"dt":1441708520,"sys":{"type":1,"id":5934,"message":0.004,"country":"AT","sunrise":1441686106,"sunset":1441732899},"id":2761369,"name":"Vienna","cod":200}`

or, with weather descriptions in German

`{"coord":{"lon":16.37,"lat":48.21},"weather":[{"id":503,"main":"Rain","description":"sehr starker Regen","icon":"10d"}],"base":"cmc stations","main":{"temp":290.94,"pressure":1023,"humidity":42,"temp_min":288.95,"temp_max":292.55},"wind":{"speed":3.6,"deg":330},"rain":{"1h":176.11},"clouds":{"all":0},"dt":1441710688,"sys":{"type":1,"id":5934,"message":0.0043,"country":"AT","sunrise":1441686108,"sunset":1441732896},"id":2775260,"name":"Innere Stadt","cod":200}`

Note that it is reporting very heavy rain, and no cloud! Also, the 'Rain' displayed on the homepage is there (in English in both cases) as 'main', but with the additional 'description' of 'sehr starker Regen', which is what we use.

The 404 for location and the missing forecasts are related. If we get an error getting the forecasts that error is displayed in place of the location. Also, unless you override this in the configuration, the displayed location (for Openweather anyway) is taken from the response to the forecast api call. The source of the displayed location can be overridden because several services offer weather text in various languages, but always return city names in English. If you're seeing 'Vienna' and would prefer 'Wien' you may find that using Google or Yahoo will help.

I recommend experimenting with different data providers to see which provides the most reliable forecasts. For me, the BBC is pretty good, but I'm in the UK and their source is the UK government Met Office (though that is changing soon). You may find a different provider is more reliable for Vienna.

Let me know if you find any more issues. And feel free to rate the desklet at http://cinnamon-spices.linuxmint.com/desklets/view/20
